language: python
python:
  - "2.7"
install: 
  - pip install --target="src/lib" -Ur requirements.txt
before_script:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.38.zip -nv
  - unzip -q google_appengine_1.9.38.zip
script: python ./src/runtests.py ./google_appengine ./src/tests
