language: python
python:
  - "2.7"
install: 
  - pip install --target="src/lib" -Ur requirements.txt
  - pip install coveralls
before_script:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.38.zip -nv
  - unzip -q google_appengine_1.9.38.zip
script:
  - coverage run --include="src/application/*" ./src/runtests.py ./google_appengine ./src/tests
after_success:
  coveralls
